---
title: "project_ess_final"
author: "Jeremy Knox"
date: "12/8/2018"
output: html_document
---

Libraries and Data Frames:
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(car)
library(userfriendlyscience)
library(knitr)
library(kableExtra)
library(effsize)
library(ggrepel)
library(reshape2)
library(stargazer)
library(Hmisc)
library(lmtest)
library(corrplot)
task1 = read_csv("climate_opinion.csv")
task2 = read.csv("ucsb_climate.csv", row.names = 1)
task3 = read_csv("tmas_df.csv")
task4 = read_csv("PesticideResidues.csv")
task5 = read_csv("ca_county_pesticides.csv")
```

Task 1: Climate Change Opinions (Yale Program on Climate Change Commu- nication)
```{r}
# correlation matrix 
sapply(task1, class)
subset_task1 = task1 %>% select(happening,consensus,discuss,mediaweekly,bachelors,poverty_rate)
cm = rcorr(as.matrix(subset_task1))
cm

# dependent "happening" is derived from a binomial variable with "yes", "no" or "dont know" responses. Then aggreagated at the state level and given as a percent of respondents who repsponded yes.
lm = lm(data = task1, happening ~ bachelors + poverty_rate + coastline) 
summary(lm) # NOT INCLUDED variables because of likely reverse causuality: "consensus", "discuss", "mediaweekly"
plot(lm) # looks homoskedastic 
bptest(lm) # p = .65 thus residuals most likley constant => homoskedastic 


##### exploring interactions => NO interactions needed ####
task1_s1 = task1 %>% 
  filter(bachelors < 40)
interaction1 = ggplot(data = task1_s1, aes(x=bachelors, y=happening, color=coastline), alpha=.1) +
  geom_point(shape=1) +
  stat_smooth(aes(group = coastline), method = "lm", formula = y ~ x, se = FALSE)
interaction1
interaction2 = ggplot(data = task1_s1, aes(x=poverty_rate, y=happening, color=coastline), alpha=.1) +
  geom_point(shape=1) +
  stat_smooth(aes(group = coastline), method = "lm", formula = y ~ x, se = FALSE)
interaction2
interaction3 = ggplot(data = task1_s1, aes(x=GeoName, y=happening, color=coastline), alpha=.1) +
  geom_point(shape=1) +
  stat_smooth(aes(group = coastline), method = "lm", formula = y ~ x, se = FALSE)
interaction3
```

Task 2: UCSB Campus Climate Survey - Perceptions of Campus Respectfulness by Respondent Race/Ethnicity
```{r}
# compare proportions
task2_simple = task2%>% 
  select(Very.Respectful,Respectful,Disrespectful,Very.Disrespectful)
chisq <- chisq.test(task2_simple)
chisq

# exploring visually
chisq$observed
round(chisq$expected,2)
round(chisq$residuals, 3)
corrplot(chisq$residuals, is.cor = FALSE)

contrib <- 100*chisq$residuals^2/chisq$statistic
round(contrib, 3)
corrplot(contrib, is.cor = FALSE)
```

Task 3: Effect of sex and age on self-consciousness (Taylor Manifest Anxiety Scale)
```{r}
sapply(task3, class)
task3 = task3 %>% 
  mutate(response = case_when(response == "True" ~ 1,
                              response == "False" ~ 0)) %>% 
  mutate(sex_mf = case_when(sex_mf == "Male" ~ 1,
                              sex_mf == "Female" ~ 0))

# cm = rcorr(as.matrix(task3))
# cm

lm = lm(data = task3, response ~ age + sex_mf) 
summary(lm) # NOT INCLUDED variables because of likely reverse causuality: "consensus", "discuss", "mediaweekly"
plot(lm) # does NOT looks homoskedastic plot3
bptest(lm) # p = 0 thus residuals most likley NOT constant => heteroskedastic 

##### exploring interactions => NO interactions needed ####
interaction = ggplot(data = task3, aes(x=age, y=response, color=sex_mf), alpha=.1) +
  geom_point(shape=1) +
  stat_smooth(aes(group = sex_mf), method = "lm", formula = y ~ x, se = FALSE)
interaction
```

Task 4: Pyraclostrobin residues on crops
```{r}
# task4 = task4 %>% 
#   select(COMMODITY, `CHEMICAL DETECTED (IF ANY)`, `AMOUNT OF CHEMICAL DETECTED (PPM)`) %>% 
#   rename(commodity = COMMODITY) %>% 
#   rename(chemical = `CHEMICAL DETECTED (IF ANY)`) %>% 
#   rename(ppm = `AMOUNT OF CHEMICAL DETECTED (PPM)`)
task4 = task4 %>% 
  mutate(detected = case_when(ppm > 0 ~ 1,
                              ppm == 0 ~ 0))
task4_simpl = task4 %>% 
  filter(commodity == "STRAWBERRY (ALL OR UNSPEC)" | commodity == "CARROTS (ROOT CROP)") %>% 
  mutate(commodity = case_when(commodity == "STRAWBERRY (ALL OR UNSPEC)" ~ "strawberry",
                   commodity == "CARROTS (ROOT CROP)" ~ "carrot")) %>% 
  filter(chemical == "PYRACLOSTROBIN")

h = ggplot(task4_simpl, aes(ppm)) +
  geom_histogram() +
  facet_wrap("commodity")
h 
qqs = ggplot(task4_simpl, aes(sample = ppm)) +
  geom_qq() + 
  facet_wrap("commodity", scales = "free") 
qqs

strawberry = task4_simpl %>% 
  filter(commodity == "strawberry") %>% 
  pull(ppm)
carrot = task4_simpl %>% 
  filter(commodity == "carrot") %>% 
  pull(ppm)

ftest = var.test(strawberry,carrot) # p=0 thus variances are NOT equal
ftest

# #Mann-Whitney U
# mwu_emp = wilcox.test(strawberry,carrot)
# mwu_emp # p = 0.3289 (not significant, ranks are equal)
# 
# effsize_emp = cohen.d(strawberry,carrot) # d estimate = 0.26 (small)
```

